### ISSUE TITLE
 gh-pages not showing proper CSS layout

### ISSUE THREAD

**Issue by rmsrosa** [rmsrosa/booksjl-franklin-template#1]

**Comment by rmsrosa** [comment]
I fixed the prepath, but it was not enough. I avoided an error I was getting with `optimize(minify=false, prerender=false)` (that was not happening with `serve()`), but it was not enough.

I have the impression I have two deploy actions running and one of them is reading the files from the root directory and overwriting the correct action.

**Comment by tlienart** [comment]
the prepath is fine you can see that here:

https://github.com/rmsrosa/booksjl-franklin-template/blob/3593ff82001fd4be4e520033862e523730a7d8d6/index.html#L10

the problem is that you didn't select `gh-pages` as the branch to build your pages from.

Repo settings > Pages > select `gh-pages` .

**Comment by rmsrosa** [comment]
Oh, right, of course! Thank you!
