### ISSUE TITLE
code highlighting

### ISSUE THREAD

**Issue by rmsrosa** [rmsrosa/booksjl-franklin-template#4]
Missing the css part for code highlighting.

**Comment by tlienart** [comment]
https://github.com/rmsrosa/booksjl-franklin-template/blob/2ecab12bfefd000f206fac14911b18555bc365fb/_layout/head.html#L23-L32

?

**Comment by tlienart** [comment]
ah no duh, it's missing from foot https://github.com/rmsrosa/booksjl-franklin-template/blob/2ecab12bfefd000f206fac14911b18555bc365fb/_layout/foot.html#L6-L10

**Comment by tlienart** [comment]
<img width="287" alt="Screenshot 2022-02-13 at 14 26 21" src="https://user-images.githubusercontent.com/10897531/153755289-513c2071-5e61-4ec0-861c-efbdc941eafc.png">

that's better, I don't like the font but that's another part of the CSS.

**Comment by rmsrosa** [comment]
Yeah, I don't like the font either, and the font size is too small compared with the rest of the text. I will look into that after I finish with the integration with Weave.
