### ISSUE TITLE
menu fun needs a bit of work

### ISSUE THREAD

**Issue by tlienart** [rmsrosa/booksjl-franklin-template#5]
red stuff is flagged by Firefox
<img width="1185" alt="Screenshot 2022-02-13 at 14 21 15" src="https://user-images.githubusercontent.com/10897531/153755099-7cf58f63-f0ef-43a5-8383-af4267f89c8a.png">

**Comment by rmsrosa** [comment]
Ah, ok. Yeah, it was a workaround that was bothering me a bit, but I didn't know it would be red flagged 😆 I will look into that. Thanks!

**Comment by tlienart** [comment]
just to clarify, it doesn't mean that the page doesn't render properly, it's just when you inspect the page source you see those and it means the browser doesn't like it (but it doesn't mean it will fail to render it properly; basically it's saying "_this is not semantic HTML, I'll do my best_")
