### ISSUE TITLE
JuliaMono-Regular not loading

### ISSUE THREAD

**Issue by rmsrosa** [rmsrosa/booksjl-franklin-template#6]
Inspector shows that the font file is being searched for in the root folder `github.com/rmsrosa`, without the prepath `booksjl-franklin-template`. The source file is set in `head.html` to be `src: url("/libs/fonts/JuliaMono-Regular.ttf");`. This apparently does not behave like say for `href="/assets/images/favicon.png"`, which does prepend the prepath automatically.

**Comment by tlienart** [comment]
in CSS stylesheets you have to use relative path for `url(...)` objects

```
url("../libs/fonts/JuliaMono-Regular.ttf")
```

**Comment by tlienart** [comment]
ah and don't put that in `head.html`, put it in your CSS stylesheet.

**Comment by rmsrosa** [comment]
> in CSS stylesheets you have to use relative path for url(...) objects

I did try that, but it became relative to each page

> ah and don't put that in head.html, put it in your CSS stylesheet.

Yeah, that makes sense. I was about to try an `hfun`, but CSS should be better and simpler.

**Comment by tlienart** [comment]
give me a sec

**Comment by tlienart** [comment]
btw I'd recommend not to use shell commands in Utils because users may get in a state where if they just use `serve` things will fail if the shell that Julia uses does not find the relevant command (e.g. `Jupyter`). Much better to do all this from within packages (e.g. Literate / Weave).

**Comment by tlienart** [comment]
E.g. in my case there's no Jupiter kernel Julia 1.7 so I get the error

```
...
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_client/kernelspec.py", line 230, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named julia-1.7
┌ Franklin Warning: in <menu_bar.md>
│ Encountered an issue processing 'menu_bar.md' in nklin-template/pages.
│ Verify, then re-start the Franklin server.
│ The error is displayed below:
│ ProcessFailedException(Base.Process[Process(`jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --execute /Users/tlienart/Desktop/tjd/booksjl-franklin-template/__site/generated/notebooks/weaved/weavejl.ipynb --allow-errors --output /Users/tlienart/Desktop/tjd/booksjl-franklin-template/__site/generated/notebooks/weaved/weavejl.ipynb`, ProcessExited(1))])
└
ERROR: failed process: Process(`jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --execute /Users/tlienart/Desktop/tjd/booksjl-franklin-template/__site/generated/notebooks/weaved/weavejl.ipynb --allow-errors --output /Users/tlienart/Desktop/tjd/booksjl-franklin-template/__site/generated/notebooks/weaved/weavejl.ipynb`, ProcessExited(1)) [1]

...
```

**Comment by tlienart** [comment]
(in fact it will likely fail on CI as well)

**Comment by rmsrosa** [comment]
Hmm, I don't remember using this explicitly in utils.jl. I think it is Weave itself. I do get some errors when Weaving to notebook, but it was not failing, it was just throwing the error in the output of the notebook.

**Comment by tlienart** [comment]
(didn't fail on CI so :+1: )

need to check the font stuff a bit more

**Comment by rmsrosa** [comment]
I guess if a user does not want to use Weave and, hence, does not have any `.jl` or `.jmd` file in `_weave`, this will not be triggered. If the user has one of those but don't want to show the links to the associated jupyter notebooks, it may just the `config.md` variable `show_link_bagdes` to false, and that won't be triggered either. If someone wants to use those, we should assume it has the jupyter stuff properly set up on the machine and everything is fine. I think I should at least document this.

**Comment by tlienart** [comment]
Ok it's fine actually we can close this; I expected JuliaMono to be applied everywhere but it's just for code actually, and that works fine:
<img width="783" alt="Screenshot 2022-02-23 at 11 15 17" src="https://user-images.githubusercontent.com/10897531/155299692-7e502b75-db4e-48c9-8f20-d8ae6a1d2ed9.png">

**Comment by tlienart** [comment]
btw loading custom fonts like this is... pretty heavy. So you might want to have an option for users not to do that. 

What you could do is to put in `head.html` something like

```
{{if use_julia_monospace}}
@font-face {
    font-family: JuliaMono-Regular;
    src: url("https://cdn.jsdelivr.net/gh/cormullion/juliamono/webfonts/JuliaMono-Regular.woff2");
}
{{end}}
```

with in `config.md` 

```
+++
...
use_julia_monospace = true
...
+++
```

**Comment by rmsrosa** [comment]
I see. I would also need to modify how CSS uses this font in code. I guess I should write a separate `juliamono_code.css` with this setting and load this css depending on whether `use_julia_monospace` is true of false. Unless there is a better way I am not seeing.

**Comment by tlienart** [comment]
I think that would be a good approach.

Note that you can always use multiple fonts in CSS in order of preference and have the browser figure out whichever one is best. So you'd have something like

```css
pre {
  font-family: JuliaMono-Regular, Helvetica, monospace;
}
```

see https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

**Comment by rmsrosa** [comment]
Yes, that is what I have already. So in fact I don't actually need to load a separate CSS. If the font is not available, it won't be used.

**Comment by rmsrosa** [comment]
Are you worried about the font being heavy in RAM, when loading the font, or being heavy in disk/repo space? It is 2.4Mb. It is not so absurd. This way it has the advantage of being available offline.

I could just add a comment in the documentation saying that one can edit the CSS to remove JuliaMono-Regular and remove the ttf from the repo.

**Comment by tlienart** [comment]
This is up to you, I personally like my pages to be under 500kb if possible and that's generally a good rule of thumb to avoid having slow loading pages. For users who do not have a very fast speed when you have pages in the 1Mb+ range, they start seeing the page being painted in seconds and it's very annoying (this is the case for the JuliaMono site for me for instance).

**Comment by rmsrosa** [comment]
I see. What do you like for code fonts, then? I can change the default and just mention how to add JuliaMono if one wants to.

**Comment by tlienart** [comment]
text:

```css
system-ui,-apple-system,"Segoe UI",Roboto,
                 "Helvetica Neue",Arial,"Noto Sans",
                 "Liberation Sans",sans-serif,"Apple Color Emoji",
                 "Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"
```

code

```css
SFMono-Regular,Menlo,Monaco,Consolas,
						     "Liberation Mono","Courier New",monospace;
```

these are standard font stacks that you can find in the likes of bootstrap and co frameworks

**Comment by rmsrosa** [comment]
Ok, you convinced me! 😄

I removed loading JuliaMono, but left it in the font list, just in case the user has it installed in their system. If not, the next available in the list is loaded.

Thanks again for all your help!

**Comment by tlienart** [comment]
I'm glad to see this project moving forward & happy if I can help!
